### ISSUE TITLE
No kernel supports rl_lstm/MatMul_7 of type MatMul

### ISSUE THREAD

**Issue by tedgoddard** [google/sling#90]
I've extracted some of the steps for running `train.sh` and `parse` into a Dockerfile:
 
https://github.com/RobotsAndPencils/sling-docker/blob/master/Dockerfile

but have run into:

```
I1117 23:52:39.514359     1 parse.cc:131] Load parser from /tmp/sempar-conll/sempar.flow
E1117 23:52:39.529886     1 compute.cc:979] No kernel supports rl_lstm/MatMul_7 of type MatMul
F1117 23:52:39.529938     1 parser.cc:67] Check failed: network_.Compile(flow, library_) 
```

(I'm not clear on whether it's necessary to install the kernels, or perhaps specific GPU support is required. Apologies in advance, since I'm not yet familiar with several of the packages used.)

**Comment by ringgaard** [comment]
It looks like the Myelin JIT compiler in SLING fails to generate code for your CPU. Could I get you to run `cat /proc/cpuinfo` (inside the docker container?) to see what features your CPU supports. Also, running nlp/parser/tools/parse with --v=9 would produce more debug output that might be helpful in determining why Myelin fails to find a kernel for generating code for rl_lstm/MatMul_7.

**Comment by GMarzinotto** [comment]
Hello!
I'm getting the same error.

> E1120 10:42:11.005601 68726 compute.cc:979]  No kernel supports rl_lstm/MatMul_7 of type MatMul

I'm able to run the pre-trained model that you provide and it works well.
I tried to train my own model with the sample dataset you provide
The training shows no error

> INFO:tensorflow:Finished training!
INFO:tensorflow:Saving
 flow to /tmp/sempar-conll/sempar.flow
INFO:tensorflow:Best checkpoint written to /tmp/sempar-conll/checkpoints/best
2017-11-17 15:33:18.148531: I third_party/syntaxnet/dragnn/core/compute_session_pool.cc:55] Destroying pool: total number of sessions created = 1
Done.


however, when I try to use the model for inference It doesn't work.
I run it with --v=9 and this is the log output


> I1120 10:34:37.888370 68554 init.cc:39] Initializing clock module
I1120 10:34:37.888475 68554 init.cc:39] Initializing filesystem module
I1120 10:34:37.888483 68554 parse.cc:131] Load parser from /home/swqh0332/sling/sling/toymodel/sempar.flow
I1120 10:34:37.888525 68554 compute.cc:385] Register Reshape for Reshape
I1120 10:34:37.888530 68554 compute.cc:385] Register Squeeze for Squeeze
I1120 10:34:37.888535 68554 compute.cc:385] Register ExpandDims for ExpandDims
I1120 10:34:37.888537 68554 compute.cc:385] Register SpaceToBatch for SpaceToBatchND
I1120 10:34:37.888541 68554 compute.cc:385] Register BatchToSpace for BatchToSpaceND
I1120 10:34:37.888545 68554 compute.cc:385] Register Pack for Pack
I1120 10:34:37.888548 68554 compute.cc:385] Register Unpack for Unpack
I1120 10:34:37.888551 68554 compute.cc:385] Register GeneralConcat for ConcatV2
I1120 10:34:37.888556 68554 compute.cc:385] Register BasicConcat for ConcatV2
I1120 10:34:37.888558 68554 compute.cc:385] Register MultiGather for Gather
I1120 10:34:37.888561 68554 compute.cc:385] Register SingleGather for Gather
I1120 10:34:37.888566 68554 compute.cc:385] Register GenFltAbs for Abs
I1120 10:34:37.888569 68554 compute.cc:385] Register GenFltSqrt for Sqrt
I1120 10:34:37.888574 68554 compute.cc:385] Register GenFltExp for Exp
I1120 10:34:37.888578 68554 compute.cc:385] Register GenFltLog for Log
I1120 10:34:37.888581 68554 compute.cc:385] Register GenFltCeil for Ceil
I1120 10:34:37.888584 68554 compute.cc:385] Register GenFltFloor for Floor
I1120 10:34:37.888588 68554 compute.cc:385] Register GenFltCos for Cos
I1120 10:34:37.888592 68554 compute.cc:385] Register GenFltSin for Sin
I1120 10:34:37.888594 68554 compute.cc:385] Register GenFltTan for Tan
I1120 10:34:37.888597 68554 compute.cc:385] Register GenFltTanh for Tanh
I1120 10:34:37.888602 68554 compute.cc:385] Register GenFltSigmoid for Sigmoid
I1120 10:34:37.888604 68554 compute.cc:385] Register GenFltRelu for Relu
I1120 10:34:37.888607 68554 compute.cc:385] Register GenFltArgMax for ArgMax
I1120 10:34:37.888612 68554 compute.cc:385] Register GenFltMatMatMul for MatMul
I1120 10:34:37.888617 68554 compute.cc:385] Register GenFltVecMatMul for MatMul
I1120 10:34:37.888620 68554 compute.cc:385] Register GenFltVecMatMulAdd for MatMulAdd
I1120 10:34:37.888624 68554 compute.cc:385] Register GenFltVecMatMulRelu for MatMulRelu
I1120 10:34:37.888628 68554 compute.cc:385] Register GenFltVecMatMulAddRelu for MatMulAddRelu
I1120 10:34:37.888631 68554 compute.cc:385] Register GenIntVecMatMul for MatMul
I1120 10:34:37.888634 68554 compute.cc:385] Register GenIntVecMatMulAdd for MatMulAdd
I1120 10:34:37.888638 68554 compute.cc:385] Register GenFltIntMatMulRelu for MatMulRelu
I1120 10:34:37.888641 68554 compute.cc:385] Register GenIntVecMatMulAddRelu for MatMulAddRelu
I1120 10:34:37.888645 68554 compute.cc:385] Register GenFltAdd for Add
I1120 10:34:37.888648 68554 compute.cc:385] Register GenFltSub for Sub
I1120 10:34:37.888653 68554 compute.cc:385] Register GenFltMul for Mul
I1120 10:34:37.888655 68554 compute.cc:385] Register GenFltConstSub for Sub
I1120 10:34:37.888659 68554 compute.cc:385] Register GenFltMulTwoAdd for MulTwoAdd
I1120 10:34:37.888662 68554 compute.cc:385] Register GenIntAdd for Add
I1120 10:34:37.888665 68554 compute.cc:385] Register GenIntSub for Sub
I1120 10:34:37.888669 68554 compute.cc:385] Register GenIntMul for Mul
I1120 10:34:37.888672 68554 compute.cc:385] Register SSEFltVecMatMul for MatMul
I1120 10:34:37.888675 68554 compute.cc:385] Register SSEFltVecMatMulAdd for MatMulAdd
I1120 10:34:37.888679 68554 compute.cc:385] Register SSEFltVecMatMulRelu for MatMulRelu
I1120 10:34:37.888682 68554 compute.cc:385] Register SSEFltVecMatMulAddRelu for MatMulAddRelu
I1120 10:34:37.888686 68554 compute.cc:385] Register AVXFltTanh for Tanh
I1120 10:34:37.888689 68554 compute.cc:385] Register AVXFltExp for Exp
I1120 10:34:37.888692 68554 compute.cc:385] Register AVXFltSigmoid for Sigmoid
I1120 10:34:37.888696 68554 compute.cc:385] Register AVXFltArgMax for ArgMax
I1120 10:34:37.888700 68554 compute.cc:385] Register AVXFltMatMatMul for MatMul
I1120 10:34:37.888703 68554 compute.cc:385] Register AVXFltVecMatMulH for MatMul
I1120 10:34:37.888707 68554 compute.cc:385] Register AVXFltVecMatMulAddH for MatMulAdd
I1120 10:34:37.888710 68554 compute.cc:385] Register AVXFltVecMatMulReluH for MatMulRelu
I1120 10:34:37.888715 68554 compute.cc:385] Register AVXFltVecMatMulAddReluH for MatMulAddRelu
I1120 10:34:37.888717 68554 compute.cc:385] Register AVXFltVecMatMulV for MatMul
I1120 10:34:37.888721 68554 compute.cc:385] Register AVXFltVecMatMulAddV for MatMulAdd
I1120 10:34:37.888725 68554 compute.cc:385] Register AVXFltVecMatMulReluV for MatMulRelu
I1120 10:34:37.888728 68554 compute.cc:385] Register AVXFltVecMatMulAddReluV for MatMulAddRelu
I1120 10:34:37.888734 68554 compute.cc:385] Register AVXIntVecMatMulH for MatMul
I1120 10:34:37.888738 68554 compute.cc:385] Register AVXIntVecMatMulAddH for MatMulAdd
I1120 10:34:37.888741 68554 compute.cc:385] Register AVXIntVecMatMulReluH for MatMulRelu
I1120 10:34:37.888746 68554 compute.cc:385] Register AVXIntVecMatMulAddReluH for MatMulAddRelu
I1120 10:34:37.888748 68554 compute.cc:385] Register AVXFltAdd for Add
I1120 10:34:37.888751 68554 compute.cc:385] Register AVXFltSub for Sub
I1120 10:34:37.888754 68554 compute.cc:385] Register AVXFltMul for Mul
I1120 10:34:37.888756 68554 compute.cc:385] Register AVXFltConstSub for Sub
I1120 10:34:37.888758 68554 compute.cc:385] Register AVXFltMulTwoAdd for MulTwoAdd
I1120 10:34:37.888761 68554 compute.cc:385] Register AVXIntAdd for Add
I1120 10:34:37.888762 68554 compute.cc:385] Register AVXIntSub for Sub
I1120 10:34:37.888764 68554 compute.cc:385] Register AddExpr for Add
I1120 10:34:37.888767 68554 compute.cc:385] Register SubExpr for Sub
I1120 10:34:37.888767 68554 compute.cc:385] Register MulExpr for Mul
I1120 10:34:37.888769 68554 compute.cc:385] Register DivExpr for Div
I1120 10:34:37.888772 68554 compute.cc:385] Register MaxExpr for Maximum
I1120 10:34:37.888773 68554 compute.cc:385] Register MinExpr for Minimum
I1120 10:34:37.888775 68554 compute.cc:385] Register LogExpr for Log
I1120 10:34:37.888777 68554 compute.cc:385] Register ExpExpr for Exp
I1120 10:34:37.888778 68554 compute.cc:385] Register SigmoidExpr for Sigmoid
I1120 10:34:37.888780 68554 compute.cc:385] Register TanhExpr for Tanh
I1120 10:34:37.888783 68554 compute.cc:385] Register Calculate for Calculate
I1120 10:34:37.888785 68554 compute.cc:385] Register NegateExpr for Negate
I1120 10:34:37.888787 68554 compute.cc:385] Register AbsExpr for Abs
I1120 10:34:37.888789 68554 compute.cc:385] Register ReluExpr for Relu
I1120 10:34:37.888792 68554 compute.cc:385] Register SoftsignExpr for Softsign
I1120 10:34:37.888793 68554 compute.cc:385] Register SoftplusExpr for Softplus
I1120 10:34:37.888794 68554 compute.cc:385] Register LogSigmoidExpr for LogSigmoid
I1120 10:34:37.888797 68554 compute.cc:385] Register ReciprocalExpr for Reciprocal
I1120 10:34:37.888798 68554 compute.cc:385] Register SquareExpr for Square
I1120 10:34:37.888800 68554 compute.cc:385] Register AddExpr for Add
I1120 10:34:37.888803 68554 compute.cc:385] Register SubExpr for Sub
I1120 10:34:37.888805 68554 compute.cc:385] Register MulExpr for Mul
I1120 10:34:37.888808 68554 compute.cc:385] Register DivExpr for Div
I1120 10:34:37.888809 68554 compute.cc:385] Register MaxExpr for Maximum
I1120 10:34:37.888811 68554 compute.cc:385] Register MinExpr for Minimum
I1120 10:34:37.888813 68554 compute.cc:385] Register LogExpr for Log
I1120 10:34:37.888814 68554 compute.cc:385] Register ExpExpr for Exp
I1120 10:34:37.888816 68554 compute.cc:385] Register SigmoidExpr for Sigmoid
I1120 10:34:37.888818 68554 compute.cc:385] Register TanhExpr for Tanh
I1120 10:34:37.888820 68554 compute.cc:385] Register Calculate for Calculate
I1120 10:34:37.888824 68554 compute.cc:385] Register NegateExpr for Negate
I1120 10:34:37.888826 68554 compute.cc:385] Register AbsExpr for Abs
I1120 10:34:37.888828 68554 compute.cc:385] Register ReluExpr for Relu
I1120 10:34:37.888829 68554 compute.cc:385] Register SoftsignExpr for Softsign
I1120 10:34:37.888831 68554 compute.cc:385] Register SoftplusExpr for Softplus
I1120 10:34:37.888833 68554 compute.cc:385] Register LogSigmoidExpr for LogSigmoid
I1120 10:34:37.888834 68554 compute.cc:385] Register ReciprocalExpr for Reciprocal
I1120 10:34:37.888836 68554 compute.cc:385] Register SquareExpr for Square
I1120 10:34:37.888839 68554 compute.cc:385] Register Reshape for Reshape
I1120 10:34:37.888840 68554 compute.cc:385] Register Squeeze for Squeeze
I1120 10:34:37.888844 68554 compute.cc:385] Register ExpandDims for ExpandDims
I1120 10:34:37.888845 68554 compute.cc:385] Register SpaceToBatch for SpaceToBatchND
I1120 10:34:37.888847 68554 compute.cc:385] Register BatchToSpace for BatchToSpaceND
I1120 10:34:37.888849 68554 compute.cc:385] Register Pack for Pack
I1120 10:34:37.888851 68554 compute.cc:385] Register Unpack for Unpack
I1120 10:34:37.888854 68554 compute.cc:385] Register GeneralConcat for ConcatV2
I1120 10:34:37.888855 68554 compute.cc:385] Register BasicConcat for ConcatV2
I1120 10:34:37.888856 68554 compute.cc:385] Register MultiGather for Gather
I1120 10:34:37.888859 68554 compute.cc:385] Register SingleGather for Gather
I1120 10:34:37.888860 68554 compute.cc:385] Register GenFltAbs for Abs
I1120 10:34:37.888862 68554 compute.cc:385] Register GenFltSqrt for Sqrt
I1120 10:34:37.888864 68554 compute.cc:385] Register GenFltExp for Exp
I1120 10:34:37.888865 68554 compute.cc:385] Register GenFltLog for Log
I1120 10:34:37.888867 68554 compute.cc:385] Register GenFltCeil for Ceil
I1120 10:34:37.888870 68554 compute.cc:385] Register GenFltFloor for Floor
I1120 10:34:37.888872 68554 compute.cc:385] Register GenFltCos for Cos
I1120 10:34:37.888873 68554 compute.cc:385] Register GenFltSin for Sin
I1120 10:34:37.888875 68554 compute.cc:385] Register GenFltTan for Tan
I1120 10:34:37.888877 68554 compute.cc:385] Register GenFltTanh for Tanh
I1120 10:34:37.888880 68554 compute.cc:385] Register GenFltSigmoid for Sigmoid
I1120 10:34:37.888880 68554 compute.cc:385] Register GenFltRelu for Relu
I1120 10:34:37.888882 68554 compute.cc:385] Register GenFltArgMax for ArgMax
I1120 10:34:37.888885 68554 compute.cc:385] Register GenFltMatMatMul for MatMul
I1120 10:34:37.888886 68554 compute.cc:385] Register GenFltVecMatMul for MatMul
I1120 10:34:37.888888 68554 compute.cc:385] Register GenFltVecMatMulAdd for MatMulAdd
I1120 10:34:37.888890 68554 compute.cc:385] Register GenFltVecMatMulRelu for MatMulRelu
I1120 10:34:37.888891 68554 compute.cc:385] Register GenFltVecMatMulAddRelu for MatMulAddRelu
I1120 10:34:37.888893 68554 compute.cc:385] Register GenIntVecMatMul for MatMul
I1120 10:34:37.888895 68554 compute.cc:385] Register GenIntVecMatMulAdd for MatMulAdd
I1120 10:34:37.888897 68554 compute.cc:385] Register GenFltIntMatMulRelu for MatMulRelu
I1120 10:34:37.888900 68554 compute.cc:385] Register GenIntVecMatMulAddRelu for MatMulAddRelu
I1120 10:34:37.888901 68554 compute.cc:385] Register GenFltAdd for Add
I1120 10:34:37.888903 68554 compute.cc:385] Register GenFltSub for Sub
I1120 10:34:37.888905 68554 compute.cc:385] Register GenFltMul for Mul
I1120 10:34:37.888906 68554 compute.cc:385] Register GenFltConstSub for Sub
I1120 10:34:37.888908 68554 compute.cc:385] Register GenFltMulTwoAdd for MulTwoAdd
I1120 10:34:37.888911 68554 compute.cc:385] Register GenIntAdd for Add
I1120 10:34:37.888911 68554 compute.cc:385] Register GenIntSub for Sub
I1120 10:34:37.888913 68554 compute.cc:385] Register GenIntMul for Mul
I1120 10:34:37.888916 68554 compute.cc:385] Register StridedSlice for StridedSlice
I1120 10:34:37.888919 68554 compute.cc:385] Register Pack2 for Pack
I1120 10:34:37.888921 68554 compute.cc:385] Register Pack3 for Pack
I1120 10:34:37.888923 68554 compute.cc:385] Register Pack4 for Pack
I1120 10:34:37.888926 68554 compute.cc:385] Register Fill1 for Fill
I1120 10:34:37.888927 68554 compute.cc:385] Register DragnnInitializerDummy for DragnnEmbeddingInitializer
I1120 10:34:37.888931 68554 compute.cc:385] Register DragnnLookup for Lookup
I1120 10:34:37.888932 68554 compute.cc:385] Register DragnnLookupUnrolled for Lookup
I1120 10:34:37.888934 68554 compute.cc:385] Register DragnnLookupSingle for Lookup
I1120 10:34:37.888936 68554 compute.cc:385] Register DragnnCollect for Collect
I1120 10:34:37.964639 68554 arithmetic.cc:279] 0 of 37 ops combined
I1120 10:34:37.964715 68554 arithmetic.cc:279] 0 of 37 ops combined
I1120 10:34:37.964808 68554 arithmetic.cc:279] 0 of 37 ops combined
I1120 10:34:37.964860 68554 arithmetic.cc:279] 0 of 37 ops combined
I1120 10:34:37.964910 68554 arithmetic.cc:279] 0 of 37 ops combined
I1120 10:34:37.965173 68554 compute.cc:983] Step lr_lstm/punctuation/Lookup implemented by DragnnLookupSingle
I1120 10:34:37.965188 68554 compute.cc:983] Step rl_lstm/hyphen/Lookup implemented by DragnnLookupSingle
I1120 10:34:37.965196 68554 compute.cc:975] DragnnLookupSingle does not support lr_lstm/suffix/Lookup
I1120 10:34:37.965201 68554 compute.cc:983] Step lr_lstm/suffix/Lookup implemented by DragnnLookupUnrolled
I1120 10:34:37.965207 68554 compute.cc:983] Step rl_lstm/capitalization/Lookup implemented by DragnnLookupSingle
I1120 10:34:37.965214 68554 compute.cc:983] Step ff/rl/Collect implemented by DragnnCollect
I1120 10:34:37.965219 68554 compute.cc:983] Step rl_lstm/quote/Lookup implemented by DragnnLookupSingle
I1120 10:34:37.965224 68554 compute.cc:983] Step ff/frame-end-lr/Collect implemented by DragnnCollect
I1120 10:34:37.965229 68554 compute.cc:983] Step ff/frame-end-rl/Collect implemented by DragnnCollect
I1120 10:34:37.965234 68554 compute.cc:983] Step rl_lstm/words/Lookup implemented by DragnnLookupSingle
I1120 10:34:37.965240 68554 compute.cc:983] Step lr_lstm/quote/Lookup implemented by DragnnLookupSingle
I1120 10:34:37.965246 68554 compute.cc:975] AVXIntVecMatMulH does not support rl_lstm/MatMul_7
I1120 10:34:37.965250 68554 compute.cc:975] AVXFltVecMatMulV does not support rl_lstm/MatMul_7
I1120 10:34:37.965255 68554 compute.cc:975] AVXFltVecMatMulH does not support rl_lstm/MatMul_7
I1120 10:34:37.965260 68554 compute.cc:975] AVXFltMatMatMul does not support rl_lstm/MatMul_7
I1120 10:34:37.965265 68554 compute.cc:975] SSEFltVecMatMul does not support rl_lstm/MatMul_7
I1120 10:34:37.965268 68554 compute.cc:975] GenIntVecMatMul does not support rl_lstm/MatMul_7
I1120 10:34:37.965273 68554 compute.cc:975] GenFltVecMatMul does not support rl_lstm/MatMul_7
I1120 10:34:37.965277 68554 compute.cc:975] GenFltMatMatMul does not support rl_lstm/MatMul_7
E1120 10:34:37.965281 68554 compute.cc:979] No kernel supports rl_lstm/MatMul_7 of type MatMul
F1120 10:34:37.965289 68554 parser.cc:67] Check failed: network_.Compile(flow, library_) 
*** Check failure stack trace: ***
    @           0x4b68ca  google::LogMessage::Fail()
    @           0x4b75da  google::LogMessage::SendToLog()
    @           0x4b65f5  google::LogMessage::Flush()
    @           0x4b7ec9  google::LogMessageFatal::~LogMessageFatal()
    @           0x414860  sling::nlp::Parser::Load()
    @           0x405c56  main
    @     0x7fd499aba830  __libc_start_main
    @           0x409cf9  _start
Abandon (core dumped)


Any insights on this? 
Thank you very much!

**Comment by tedgoddard** [comment]
It looks like the bogomips are different for each one, but the flags are consistent:

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
stepping	: 9
cpu MHz		: 3100.000
cache size	: 8192 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 hle avx2 bmi2 erms rtm xsaveopt arat
bugs		:
bogomips	: 6192.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
stepping	: 9
cpu MHz		: 3100.000
cache size	: 8192 KB
physical id	: 1
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 hle avx2 bmi2 erms rtm xsaveopt arat
bugs		:
bogomips	: 6660.46
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
stepping	: 9
cpu MHz		: 3100.000
cache size	: 8192 KB
physical id	: 2
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 hle avx2 bmi2 erms rtm xsaveopt arat
bugs		:
bogomips	: 6271.87
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
stepping	: 9
cpu MHz		: 3100.000
cache size	: 8192 KB
physical id	: 3
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 hle avx2 bmi2 erms rtm xsaveopt arat
bugs		:
bogomips	: 6079.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

I'll try building on a Ryzen/Linux system (the above is docker on a MacBook Pro 2017).

**Comment by tedgoddard** [comment]
And here's my detailed log output:

```
I1120 19:36:45.460611     9 init.cc:39] Initializing clock module
I1120 19:36:46.462591     9 init.cc:39] Initializing filesystem module
I1120 19:36:46.462633     9 parse.cc:131] Load parser from /tmp/sempar-conll/sempar.flow
I1120 19:36:46.462689     9 compute.cc:385] Register Reshape for Reshape
I1120 19:36:46.462708     9 compute.cc:385] Register Squeeze for Squeeze
I1120 19:36:46.462725     9 compute.cc:385] Register ExpandDims for ExpandDims
I1120 19:36:46.462730     9 compute.cc:385] Register SpaceToBatch for SpaceToBatchND
I1120 19:36:46.462735     9 compute.cc:385] Register BatchToSpace for BatchToSpaceND
I1120 19:36:46.462740     9 compute.cc:385] Register Pack for Pack
I1120 19:36:46.462754     9 compute.cc:385] Register Unpack for Unpack
I1120 19:36:46.462760     9 compute.cc:385] Register GeneralConcat for ConcatV2
I1120 19:36:46.462765     9 compute.cc:385] Register BasicConcat for ConcatV2
I1120 19:36:46.462770     9 compute.cc:385] Register MultiGather for Gather
I1120 19:36:46.462785     9 compute.cc:385] Register SingleGather for Gather
I1120 19:36:46.462790     9 compute.cc:385] Register GenFltAbs for Abs
I1120 19:36:46.462805     9 compute.cc:385] Register GenFltSqrt for Sqrt
I1120 19:36:46.462808     9 compute.cc:385] Register GenFltExp for Exp
I1120 19:36:46.462815     9 compute.cc:385] Register GenFltLog for Log
I1120 19:36:46.462821     9 compute.cc:385] Register GenFltCeil for Ceil
I1120 19:36:46.462834     9 compute.cc:385] Register GenFltFloor for Floor
I1120 19:36:46.462839     9 compute.cc:385] Register GenFltCos for Cos
I1120 19:36:46.462843     9 compute.cc:385] Register GenFltSin for Sin
I1120 19:36:46.462848     9 compute.cc:385] Register GenFltTan for Tan
I1120 19:36:46.462852     9 compute.cc:385] Register GenFltTanh for Tanh
I1120 19:36:46.462857     9 compute.cc:385] Register GenFltSigmoid for Sigmoid
I1120 19:36:46.462862     9 compute.cc:385] Register GenFltRelu for Relu
I1120 19:36:46.462874     9 compute.cc:385] Register GenFltArgMax for ArgMax
I1120 19:36:46.462882     9 compute.cc:385] Register GenFltMatMatMul for MatMul
I1120 19:36:46.462898     9 compute.cc:385] Register GenFltVecMatMul for MatMul
I1120 19:36:46.462911     9 compute.cc:385] Register GenFltVecMatMulAdd for MatMulAdd
I1120 19:36:46.462915     9 compute.cc:385] Register GenFltVecMatMulRelu for MatMulRelu
I1120 19:36:46.462929     9 compute.cc:385] Register GenFltVecMatMulAddRelu for MatMulAddRelu
I1120 19:36:46.462934     9 compute.cc:385] Register GenIntVecMatMul for MatMul
I1120 19:36:46.462940     9 compute.cc:385] Register GenIntVecMatMulAdd for MatMulAdd
I1120 19:36:46.462994     9 compute.cc:385] Register GenFltIntMatMulRelu for MatMulRelu
I1120 19:36:46.463001     9 compute.cc:385] Register GenIntVecMatMulAddRelu for MatMulAddRelu
I1120 19:36:46.463011     9 compute.cc:385] Register GenFltAdd for Add
I1120 19:36:46.463016     9 compute.cc:385] Register GenFltSub for Sub
I1120 19:36:46.463021     9 compute.cc:385] Register GenFltMul for Mul
I1120 19:36:46.463027     9 compute.cc:385] Register GenFltConstSub for Sub
I1120 19:36:46.463032     9 compute.cc:385] Register GenFltMulTwoAdd for MulTwoAdd
I1120 19:36:46.463399     9 compute.cc:385] Register GenIntAdd for Add
I1120 19:36:46.463404     9 compute.cc:385] Register GenIntSub for Sub
I1120 19:36:46.463409     9 compute.cc:385] Register GenIntMul for Mul
I1120 19:36:46.463415     9 compute.cc:385] Register SSEFltVecMatMul for MatMul
I1120 19:36:46.463418     9 compute.cc:385] Register SSEFltVecMatMulAdd for MatMulAdd
I1120 19:36:46.463428     9 compute.cc:385] Register SSEFltVecMatMulRelu for MatMulRelu
I1120 19:36:46.463436     9 compute.cc:385] Register SSEFltVecMatMulAddRelu for MatMulAddRelu
I1120 19:36:46.463452     9 compute.cc:385] Register AVXFltTanh for Tanh
I1120 19:36:46.463466     9 compute.cc:385] Register AVXFltExp for Exp
I1120 19:36:46.463472     9 compute.cc:385] Register AVXFltSigmoid for Sigmoid
I1120 19:36:46.463476     9 compute.cc:385] Register AVXFltArgMax for ArgMax
I1120 19:36:46.463490     9 compute.cc:385] Register AVXFltMatMatMul for MatMul
I1120 19:36:46.463539     9 compute.cc:385] Register AVXFltVecMatMulH for MatMul
I1120 19:36:46.463546     9 compute.cc:385] Register AVXFltVecMatMulAddH for MatMulAdd
I1120 19:36:46.463554     9 compute.cc:385] Register AVXFltVecMatMulReluH for MatMulRelu
I1120 19:36:46.463559     9 compute.cc:385] Register AVXFltVecMatMulAddReluH for MatMulAddRelu
I1120 19:36:46.463568     9 compute.cc:385] Register AVXFltVecMatMulV for MatMul
I1120 19:36:46.463588     9 compute.cc:385] Register AVXFltVecMatMulAddV for MatMulAdd
I1120 19:36:46.463747     9 compute.cc:385] Register AVXFltVecMatMulReluV for MatMulRelu
I1120 19:36:46.463752     9 compute.cc:385] Register AVXFltVecMatMulAddReluV for MatMulAddRelu
I1120 19:36:46.463771     9 compute.cc:385] Register AVXIntVecMatMulH for MatMul
I1120 19:36:46.463793     9 compute.cc:385] Register AVXIntVecMatMulAddH for MatMulAdd
I1120 19:36:46.463840     9 compute.cc:385] Register AVXIntVecMatMulReluH for MatMulRelu
I1120 19:36:46.463850     9 compute.cc:385] Register AVXIntVecMatMulAddReluH for MatMulAddRelu
I1120 19:36:46.463917     9 compute.cc:385] Register AVXFltAdd for Add
I1120 19:36:46.463924     9 compute.cc:385] Register AVXFltSub for Sub
I1120 19:36:46.463928     9 compute.cc:385] Register AVXFltMul for Mul
I1120 19:36:46.463934     9 compute.cc:385] Register AVXFltConstSub for Sub
I1120 19:36:46.463949     9 compute.cc:385] Register AVXFltMulTwoAdd for MulTwoAdd
I1120 19:36:46.464061     9 compute.cc:385] Register AVXIntAdd for Add
I1120 19:36:46.464066     9 compute.cc:385] Register AVXIntSub for Sub
I1120 19:36:46.464085     9 compute.cc:385] Register AddExpr for Add
I1120 19:36:46.464102     9 compute.cc:385] Register SubExpr for Sub
I1120 19:36:46.464174     9 compute.cc:385] Register MulExpr for Mul
I1120 19:36:46.464190     9 compute.cc:385] Register DivExpr for Div
I1120 19:36:46.464196     9 compute.cc:385] Register MaxExpr for Maximum
I1120 19:36:46.464201     9 compute.cc:385] Register MinExpr for Minimum
I1120 19:36:46.464205     9 compute.cc:385] Register LogExpr for Log
I1120 19:36:46.464210     9 compute.cc:385] Register ExpExpr for Exp
I1120 19:36:46.464215     9 compute.cc:385] Register SigmoidExpr for Sigmoid
I1120 19:36:46.464217     9 compute.cc:385] Register TanhExpr for Tanh
I1120 19:36:46.464222     9 compute.cc:385] Register Calculate for Calculate
I1120 19:36:46.464304     9 compute.cc:385] Register NegateExpr for Negate
I1120 19:36:46.464324     9 compute.cc:385] Register AbsExpr for Abs
I1120 19:36:46.464334     9 compute.cc:385] Register ReluExpr for Relu
I1120 19:36:46.464385     9 compute.cc:385] Register SoftsignExpr for Softsign
I1120 19:36:46.464393     9 compute.cc:385] Register SoftplusExpr for Softplus
I1120 19:36:46.464406     9 compute.cc:385] Register LogSigmoidExpr for LogSigmoid
I1120 19:36:46.464412     9 compute.cc:385] Register ReciprocalExpr for Reciprocal
I1120 19:36:46.464418     9 compute.cc:385] Register SquareExpr for Square
I1120 19:36:46.464426     9 compute.cc:385] Register AddExpr for Add
I1120 19:36:46.464433     9 compute.cc:385] Register SubExpr for Sub
I1120 19:36:46.464450     9 compute.cc:385] Register MulExpr for Mul
I1120 19:36:46.464462     9 compute.cc:385] Register DivExpr for Div
I1120 19:36:46.464479     9 compute.cc:385] Register MaxExpr for Maximum
I1120 19:36:46.464488     9 compute.cc:385] Register MinExpr for Minimum
I1120 19:36:46.464500     9 compute.cc:385] Register LogExpr for Log
I1120 19:36:46.464507     9 compute.cc:385] Register ExpExpr for Exp
I1120 19:36:46.464529     9 compute.cc:385] Register SigmoidExpr for Sigmoid
I1120 19:36:46.464536     9 compute.cc:385] Register TanhExpr for Tanh
I1120 19:36:46.464545     9 compute.cc:385] Register Calculate for Calculate
I1120 19:36:46.464550     9 compute.cc:385] Register NegateExpr for Negate
I1120 19:36:46.464565     9 compute.cc:385] Register AbsExpr for Abs
I1120 19:36:46.464573     9 compute.cc:385] Register ReluExpr for Relu
I1120 19:36:46.464591     9 compute.cc:385] Register SoftsignExpr for Softsign
I1120 19:36:46.464624     9 compute.cc:385] Register SoftplusExpr for Softplus
I1120 19:36:46.464635     9 compute.cc:385] Register LogSigmoidExpr for LogSigmoid
I1120 19:36:46.464648     9 compute.cc:385] Register ReciprocalExpr for Reciprocal
I1120 19:36:46.464653     9 compute.cc:385] Register SquareExpr for Square
I1120 19:36:46.464669     9 compute.cc:385] Register Reshape for Reshape
I1120 19:36:46.464673     9 compute.cc:385] Register Squeeze for Squeeze
I1120 19:36:46.464691     9 compute.cc:385] Register ExpandDims for ExpandDims
I1120 19:36:46.464701     9 compute.cc:385] Register SpaceToBatch for SpaceToBatchND
I1120 19:36:46.464709     9 compute.cc:385] Register BatchToSpace for BatchToSpaceND
I1120 19:36:46.464711     9 compute.cc:385] Register Pack for Pack
I1120 19:36:46.464715     9 compute.cc:385] Register Unpack for Unpack
I1120 19:36:46.464721     9 compute.cc:385] Register GeneralConcat for ConcatV2
I1120 19:36:46.464727     9 compute.cc:385] Register BasicConcat for ConcatV2
I1120 19:36:46.464749     9 compute.cc:385] Register MultiGather for Gather
I1120 19:36:46.464768     9 compute.cc:385] Register SingleGather for Gather
I1120 19:36:46.464774     9 compute.cc:385] Register GenFltAbs for Abs
I1120 19:36:46.464782     9 compute.cc:385] Register GenFltSqrt for Sqrt
I1120 19:36:46.464818     9 compute.cc:385] Register GenFltExp for Exp
I1120 19:36:46.464828     9 compute.cc:385] Register GenFltLog for Log
I1120 19:36:46.464864     9 compute.cc:385] Register GenFltCeil for Ceil
I1120 19:36:46.464879     9 compute.cc:385] Register GenFltFloor for Floor
I1120 19:36:46.464900     9 compute.cc:385] Register GenFltCos for Cos
I1120 19:36:46.464920     9 compute.cc:385] Register GenFltSin for Sin
I1120 19:36:46.464927     9 compute.cc:385] Register GenFltTan for Tan
I1120 19:36:46.464951     9 compute.cc:385] Register GenFltTanh for Tanh
I1120 19:36:46.464958     9 compute.cc:385] Register GenFltSigmoid for Sigmoid
I1120 19:36:46.464962     9 compute.cc:385] Register GenFltRelu for Relu
I1120 19:36:46.464975     9 compute.cc:385] Register GenFltArgMax for ArgMax
I1120 19:36:46.464993     9 compute.cc:385] Register GenFltMatMatMul for MatMul
I1120 19:36:46.465008     9 compute.cc:385] Register GenFltVecMatMul for MatMul
I1120 19:36:46.465014     9 compute.cc:385] Register GenFltVecMatMulAdd for MatMulAdd
I1120 19:36:46.465023     9 compute.cc:385] Register GenFltVecMatMulRelu for MatMulRelu
I1120 19:36:46.465029     9 compute.cc:385] Register GenFltVecMatMulAddRelu for MatMulAddRelu
I1120 19:36:46.465042     9 compute.cc:385] Register GenIntVecMatMul for MatMul
I1120 19:36:46.465050     9 compute.cc:385] Register GenIntVecMatMulAdd for MatMulAdd
I1120 19:36:46.465054     9 compute.cc:385] Register GenFltIntMatMulRelu for MatMulRelu
I1120 19:36:46.465056     9 compute.cc:385] Register GenIntVecMatMulAddRelu for MatMulAddRelu
I1120 19:36:46.465061     9 compute.cc:385] Register GenFltAdd for Add
I1120 19:36:46.465067     9 compute.cc:385] Register GenFltSub for Sub
I1120 19:36:46.465075     9 compute.cc:385] Register GenFltMul for Mul
I1120 19:36:46.465095     9 compute.cc:385] Register GenFltConstSub for Sub
I1120 19:36:46.465103     9 compute.cc:385] Register GenFltMulTwoAdd for MulTwoAdd
I1120 19:36:46.465111     9 compute.cc:385] Register GenIntAdd for Add
I1120 19:36:46.465133     9 compute.cc:385] Register GenIntSub for Sub
I1120 19:36:46.465144     9 compute.cc:385] Register GenIntMul for Mul
I1120 19:36:46.465150     9 compute.cc:385] Register StridedSlice for StridedSlice
I1120 19:36:46.465157     9 compute.cc:385] Register Pack2 for Pack
I1120 19:36:46.465162     9 compute.cc:385] Register Pack3 for Pack
I1120 19:36:46.465169     9 compute.cc:385] Register Pack4 for Pack
I1120 19:36:46.465183     9 compute.cc:385] Register Fill1 for Fill
I1120 19:36:46.465189     9 compute.cc:385] Register DragnnInitializerDummy for DragnnEmbeddingInitializer
I1120 19:36:46.465205     9 compute.cc:385] Register DragnnLookup for Lookup
I1120 19:36:46.465214     9 compute.cc:385] Register DragnnLookupUnrolled for Lookup
I1120 19:36:46.465219     9 compute.cc:385] Register DragnnLookupSingle for Lookup
I1120 19:36:46.465225     9 compute.cc:385] Register DragnnCollect for Collect
I1120 19:36:46.475363     9 arithmetic.cc:279] 0 of 37 ops combined
I1120 19:36:46.475437     9 arithmetic.cc:279] 0 of 37 ops combined
I1120 19:36:46.475550     9 arithmetic.cc:279] 0 of 37 ops combined
I1120 19:36:46.475654     9 arithmetic.cc:279] 0 of 37 ops combined
I1120 19:36:46.475873     9 arithmetic.cc:279] 0 of 37 ops combined
I1120 19:36:46.476300     9 compute.cc:983] Step lr_lstm/punctuation/Lookup implemented by DragnnLookupSingle
I1120 19:36:46.476332     9 compute.cc:983] Step rl_lstm/hyphen/Lookup implemented by DragnnLookupSingle
I1120 19:36:46.476342     9 compute.cc:975] DragnnLookupSingle does not support lr_lstm/suffix/Lookup
I1120 19:36:46.476348     9 compute.cc:983] Step lr_lstm/suffix/Lookup implemented by DragnnLookupUnrolled
I1120 19:36:46.476354     9 compute.cc:983] Step rl_lstm/capitalization/Lookup implemented by DragnnLookupSingle
I1120 19:36:46.476371     9 compute.cc:983] Step ff/rl/Collect implemented by DragnnCollect
I1120 19:36:46.476377     9 compute.cc:983] Step rl_lstm/quote/Lookup implemented by DragnnLookupSingle
I1120 19:36:46.476393     9 compute.cc:983] Step ff/frame-end-lr/Collect implemented by DragnnCollect
I1120 19:36:46.476403     9 compute.cc:983] Step ff/frame-end-rl/Collect implemented by DragnnCollect
I1120 19:36:46.476409     9 compute.cc:983] Step rl_lstm/words/Lookup implemented by DragnnLookupSingle
I1120 19:36:46.476423     9 compute.cc:983] Step lr_lstm/quote/Lookup implemented by DragnnLookupSingle
I1120 19:36:46.476431     9 compute.cc:975] AVXIntVecMatMulH does not support rl_lstm/MatMul_7
I1120 19:36:46.476438     9 compute.cc:975] AVXFltVecMatMulV does not support rl_lstm/MatMul_7
I1120 19:36:46.476442     9 compute.cc:975] AVXFltVecMatMulH does not support rl_lstm/MatMul_7
I1120 19:36:46.476503     9 compute.cc:975] AVXFltMatMatMul does not support rl_lstm/MatMul_7
I1120 19:36:46.476511     9 compute.cc:975] SSEFltVecMatMul does not support rl_lstm/MatMul_7
I1120 19:36:46.476514     9 compute.cc:975] GenIntVecMatMul does not support rl_lstm/MatMul_7
I1120 19:36:46.476521     9 compute.cc:975] GenFltVecMatMul does not support rl_lstm/MatMul_7
I1120 19:36:46.476526     9 compute.cc:975] GenFltMatMatMul does not support rl_lstm/MatMul_7
E1120 19:36:46.476541     9 compute.cc:979] No kernel supports rl_lstm/MatMul_7 of type MatMul
F1120 19:36:46.476550     9 parser.cc:67] Check failed: network_.Compile(flow, library_) 
*** Check failure stack trace: ***
    @           0x4b68ca  google::LogMessage::Fail()
    @           0x4b75da  google::LogMessage::SendToLog()
    @           0x4b65f5  google::LogMessage::Flush()
    @           0x4b7ec9  google::LogMessageFatal::~LogMessageFatal()
    @           0x414860  sling::nlp::Parser::Load()
    @           0x405c56  main
    @     0x7f60d7813830  __libc_start_main
    @           0x409cf9  _start
/usr/local/sling/startup.sh: line 7:     9 Aborted                 ./bazel-bin/nlp/parser/tools/parse --logtostderr --parser=/tmp/sempar-conll/sempar.flow --text="John loves Mary" --indent=2 --v=9
```

**Comment by ringgaard** [comment]
I have looked into this issue, and the problem seems to be that the flow file generated from training on the CoNLL data set have tensor sizes that are not resolved at runtime by Myelin. This problem does not depend on the particular CPU. I have made a fix for this problem in PR #93.

**Comment by tedgoddard** [comment]
On docker on an AMD/Linux system the logs (from the same Dockerfile) contain:

```
I1121 18:01:17.407241     8 compute.cc:975] AVXIntVecMatMulAddH does not support rl_lstm/MatMul_7
I1121 18:01:17.407246     8 compute.cc:983] Step rl_lstm/MatMul_7 implemented by AVXFltVecMatMulAddV
```

I will test https://github.com/google/sling/pull/93

**Comment by tedgoddard** [comment]
Verified fixed with Docker on macOS. Thanks so much for your help.
